"""event slug published_at and registrations

Revision ID: 3e5a1423df7f
Revises: 9583c4348b76
Create Date: 2026-07-03 15:24:26.168043+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3e5a1423df7f"
down_revision: str | None = "9583c4348b76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_registrations",
        sa.Column("native_event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("registered", "waitlisted", "cancelled", name="registration_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["native_event_id"], ["native_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("native_event_id", "user_id", name="uq_registration"),
    )
    op.create_index(
        op.f("ix_event_registrations_native_event_id"),
        "event_registrations",
        ["native_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_user_id"), "event_registrations", ["user_id"], unique=False
    )
    op.add_column("native_events", sa.Column("slug", sa.String(length=120), nullable=False))
    op.add_column(
        "native_events", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint("uq_native_events_slug", "native_events", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("uq_native_events_slug", "native_events", type_="unique")
    op.drop_column("native_events", "published_at")
    op.drop_column("native_events", "slug")
    op.drop_index(op.f("ix_event_registrations_user_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_native_event_id"), table_name="event_registrations")
    op.drop_table("event_registrations")
    # Drop the enum type explicitly (autogenerate does not do this).
    sa.Enum(name="registration_status").drop(op.get_bind(), checkfirst=True)
