"""initial profiles

Revision ID: 716024f441aa
Revises:
Create Date: 2026-07-03 10:20:50.910770+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "716024f441aa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("handle", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "registered", "organizer", "moderator", "admin", "super_admin", name="user_role"
            ),
            nullable=False,
        ),
        sa.Column("is_organizer", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("handle"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("profiles")
    # Drop the enum type explicitly (autogenerate does not do this).
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
