"""native events

Revision ID: 9583c4348b76
Revises: 57e5f1319551
Create Date: 2026-07-03 14:47:59.749334+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9583c4348b76"
down_revision: str | None = "57e5f1319551"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "native_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "preview",
                "pending_review",
                "published",
                "hidden",
                "cancelled",
                "archived",
                name="event_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "event_type", sa.Enum("online", "offline", "hybrid", name="event_type"), nullable=False
        ),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", "unlisted", name="event_visibility"),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("venue_address", sa.String(length=400), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("registration_required", sa.Boolean(), nullable=False),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cover_image_url", sa.String(length=1024), nullable=True),
        sa.Column("refund_policy", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_native_events_city"), "native_events", ["city"], unique=False)
    op.create_index(
        op.f("ix_native_events_organization_id"), "native_events", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_native_events_status"), "native_events", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_native_events_status"), table_name="native_events")
    op.drop_index(op.f("ix_native_events_organization_id"), table_name="native_events")
    op.drop_index(op.f("ix_native_events_city"), table_name="native_events")
    op.drop_table("native_events")
    # Drop the enum types explicitly (autogenerate does not do this).
    for enum_name in ("event_status", "event_type", "event_visibility"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
