"""imported events and sync runs

Revision ID: f4ddd2bc71be
Revises: 3e5a1423df7f
Create Date: 2026-07-03 17:50:13.674394+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f4ddd2bc71be"
down_revision: str | None = "3e5a1423df7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imported_events",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("venue", sa.String(length=300), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("dedup_hash", sa.String(length=40), nullable=False),
        sa.Column("canonical_group_id", sa.UUID(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "expired", "suppressed", name="imported_status"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_imported_provider_external"),
    )
    op.create_index(
        op.f("ix_imported_events_canonical_group_id"),
        "imported_events",
        ["canonical_group_id"],
        unique=False,
    )
    op.create_index(op.f("ix_imported_events_city"), "imported_events", ["city"], unique=False)
    op.create_index(
        op.f("ix_imported_events_dedup_hash"), "imported_events", ["dedup_hash"], unique=False
    )
    op.create_index(
        op.f("ix_imported_events_provider"), "imported_events", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_imported_events_start_time"), "imported_events", ["start_time"], unique=False
    )
    op.create_index(op.f("ix_imported_events_status"), "imported_events", ["status"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "success", "partial", "failed", name="sync_status"),
            nullable=False,
        ),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_imported_events_status"), table_name="imported_events")
    op.drop_index(op.f("ix_imported_events_start_time"), table_name="imported_events")
    op.drop_index(op.f("ix_imported_events_provider"), table_name="imported_events")
    op.drop_index(op.f("ix_imported_events_dedup_hash"), table_name="imported_events")
    op.drop_index(op.f("ix_imported_events_city"), table_name="imported_events")
    op.drop_index(op.f("ix_imported_events_canonical_group_id"), table_name="imported_events")
    op.drop_table("imported_events")
    # Drop enum types explicitly (autogenerate does not do this).
    for enum_name in ("imported_status", "sync_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
